### ISSUE TITLE
Locca build with .intentdefinition file

### ISSUE THREAD

**Issue by rafaelescoffier** [eshurakov/locca#4]
When running locca build (Locca 2.2.4) after adding translation to a .intentdefinition file, the build command (and pretty much all others) returns this error `error: genstrings failed`

**Comment by eshurakov** [comment]
Hi Rafael, could you try to fix it yourself? :-)
You can clone the repository, then run `bundle install` to install all needed dependencies.
After that, you can build & run locca via `bundle exec bin/locca`

I think the issue is that `. intentdefinition` is part of build phase and is passed to genstrings. The code related to it is in `https://github.com/eshurakov/locca/blob/master/lib/locca/projects/xcode_project.rb`

**Comment by rafaelescoffier** [comment]
Thanks, I will try

**Comment by iangmaia** [comment]
I'm actually having the exact same issue on a personal project where I'm using locca (and I'm not using `.intentdefinition`, it just stopped working when I upgraded the project to Xcode 11, I think).

@rafaelescoffier 's PR seems to work.

**Comment by eshurakov** [comment]
Thanks @rafaelescoffier, @iangmaia.
Published the updated Locca on ruby gems: https://rubygems.org/gems/locca/versions/2.2.5

**Comment by rafaelescoffier** [comment]
@eshurakov Thanks 👍
